blank_issues_enabled: false
contact_links:
  - name: ðŸ“˜ Project Scope & Contribution Policy
    url: https://github.com/spring-ai-community/spring-ai-playground/blob/HEAD/README.md#contributing--scope
    about: Please read our policy on feature requests before submitting.